# Generated by Django 4.1 on 2022-08-31 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2010, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(2010)])),
            ],
        ),
        migrations.CreateModel(
            name='TechSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1250, validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(1250)])),
                ('wheel_drive_type', models.CharField(max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
