# Generated by Django 4.1 on 2022-09-01 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techspec',
            name='hp',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(100)]),
        ),
    ]
