# Generated by Django 4.1 on 2022-09-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_techspec_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='techspec',
            name='engine_type',
            field=models.CharField(default='Petrol', max_length=10),
        ),
    ]
