# Generated by Django 4.1 on 2022-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_techspec_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='photos/car.jpg', upload_to='photos/'),
        ),
    ]
