# Generated by Django 4.1 on 2022-09-08 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0008_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='header',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
